ryan = User.create(:name => "Ryan", :email => "ryan@gmail.com", :password_hash => "ryan")
david = User.create(:name => "David", :email => "david@gmail.com", :password_hash => "david")

Album.create(:title => "Mountains", :user_id => ryan.id)
Album.create(:title => "Oceans", :user_id => david.id)
Album.create(:title => "Cats", :user_id => ryan.id)
Album.create(:title => "Dogs", :user_id => david.id)
Album.create(:title => "Hats", :user_id => ryan.id)
Album.create(:title => "Shirts", :user_id => david.id)
Album.create(:title => "Pizzas", :user_id => ryan.id)
Album.create(:title => "Hotdogs", :user_id => david.id)

Photo.create(:url => 'a.jpg', :album_id => 1)
Photo.create(:url => 'b.jpg', :album_id => 2)
Photo.create(:url => 'c.jpg', :album_id => 3)
Photo.create(:url => 'd.jpg', :album_id => 4)
Photo.create(:url => 'e.jpg', :album_id => 5)
Photo.create(:url => 'f.jpeg', :album_id => 6)
Photo.create(:url => 'g.jpeg', :album_id => 7)
Photo.create(:url => 'h.jpeg', :album_id => 8)
Photo.create(:url => 'i.jpg', :album_id => 1)
Photo.create(:url => 'j.jpg', :album_id => 2)
Photo.create(:url => 'k.jpg', :album_id => 3)
Photo.create(:url => 'l.jpg', :album_id => 4)
